"""add member_invites and role fixes

Revision ID: 37d00133d106
Revises: 6d0209aeb8a3
Create Date: 2026-03-01 23:42:54.935476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d00133d106'
down_revision: Union[str, Sequence[str], None] = '6d0209aeb8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_invites',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('scope_type', sa.Enum('DSO', 'CLINIC', name='scope_type_enum'), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='role_type_enum'), nullable=False),
    sa.Column('dso_id', sa.String(), nullable=True),
    sa.Column('clinic_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dso_id'], ['Dsos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_member_invites_id'), 'member_invites', ['id'], unique=True)
    op.create_table('role_assignments',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scope_type', sa.Enum('DSO', 'CLINIC', name='scope_type_enum'), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='role_type_enum'), nullable=False),
    sa.Column('dso_id', sa.String(), nullable=True),
    sa.Column('clinic_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dso_id'], ['Dsos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_assignments_id'), 'role_assignments', ['id'], unique=True)
    op.drop_index(op.f('ix_userclinic_id'), table_name='userclinic')
    op.drop_table('userclinic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userclinic',
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('clinic_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], name=op.f('userclinic_clinic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('userclinic_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('userclinic_pkey'))
    )
    op.create_index(op.f('ix_userclinic_id'), 'userclinic', ['id'], unique=True)
    op.drop_index(op.f('ix_role_assignments_id'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_member_invites_id'), table_name='member_invites')
    op.drop_table('member_invites')
    # ### end Alembic commands ###
