"""add clinic health fields

Revision ID: 65b51477c45e
Revises: 5fb0f36cad8e
Create Date: 2026-04-14 19:19:49.069582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b51477c45e'
down_revision: Union[str, Sequence[str], None] = '5fb0f36cad8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_inbound_events_clinic_received_at', 'inbound_events', ['clinic_id', 'received_at'], unique=False)
    op.add_column('registered_clinics', sa.Column('last_webhook_auth_failed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('registered_clinics', sa.Column('webhook_auth_failure_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('registered_clinics', sa.Column('od_health_status', sa.String(), nullable=True))
    op.add_column('registered_clinics', sa.Column('od_health_reason', sa.String(), nullable=True))
    op.add_column('registered_clinics', sa.Column('od_health_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('registered_clinics', sa.Column('crm_health_status', sa.String(), nullable=True))
    op.add_column('registered_clinics', sa.Column('crm_health_reason', sa.String(), nullable=True))
    op.add_column('registered_clinics', sa.Column('crm_health_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_clinics', 'crm_health_changed_at')
    op.drop_column('registered_clinics', 'crm_health_reason')
    op.drop_column('registered_clinics', 'crm_health_status')
    op.drop_column('registered_clinics', 'od_health_changed_at')
    op.drop_column('registered_clinics', 'od_health_reason')
    op.drop_column('registered_clinics', 'od_health_status')
    op.drop_column('registered_clinics', 'webhook_auth_failure_count')
    op.drop_column('registered_clinics', 'last_webhook_auth_failed_at')
    op.drop_index('ix_inbound_events_clinic_received_at', table_name='inbound_events')
    # ### end Alembic commands ###
