"""add sync log indexes

Revision ID: 6663de09cbc9
Revises: 1c46c799b02d
Create Date: 2026-04-10 13:20:24.841801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6663de09cbc9'
down_revision: Union[str, Sequence[str], None] = '1c46c799b02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sync_logs_clinic_started_id', 'appointment_sync_logs', ['clinic_id', 'started_at', 'id'], unique=False)
    op.create_index('ix_sync_logs_clinic_status_started_at', 'appointment_sync_logs', ['clinic_id', 'sync_status', 'started_at', 'id'], unique=False)
    op.create_index('ix_sync_logs_started_id', 'appointment_sync_logs', ['started_at', 'id'], unique=False)
    op.create_index(op.f('ix_registered_clinics_dso_id'), 'registered_clinics', ['dso_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registered_clinics_dso_id'), table_name='registered_clinics')
    op.drop_index('ix_sync_logs_started_id', table_name='appointment_sync_logs')
    op.drop_index('ix_sync_logs_clinic_status_started_at', table_name='appointment_sync_logs')
    op.drop_index('ix_sync_logs_clinic_started_id', table_name='appointment_sync_logs')
    # ### end Alembic commands ###
