"""sync latest model changes

Revision ID: 6d0209aeb8a3
Revises: 4b78552f4ce6
Create Date: 2026-02-27 09:08:36.129912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d0209aeb8a3'
down_revision: Union[str, Sequence[str], None] = '4b78552f4ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=True)
    op.create_table('userclinic',
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userclinic_id'), 'userclinic', ['id'], unique=True)
    op.create_unique_constraint('uq_dso_user_id', 'Dsos', ['user_id'])
    op.add_column('appointments', sa.Column('date', sa.String(), nullable=False))
    op.add_column('appointments', sa.Column('commslog_done', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointments', sa.Column('popups_done', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('appointments', 'AptNum',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('registered_clinics', sa.Column('location_id', sa.String(), nullable=False))
    op.add_column('registered_clinics', sa.Column('calendar_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('refresh_jti', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_jti')
    op.drop_column('users', 'token_version')
    op.drop_column('registered_clinics', 'calendar_id')
    op.drop_column('registered_clinics', 'location_id')
    op.alter_column('appointments', 'start_time',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('appointments', 'AptNum',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'popups_done')
    op.drop_column('appointments', 'commslog_done')
    op.drop_column('appointments', 'date')
    op.drop_constraint('uq_dso_user_id', 'Dsos', type_='unique')
    op.drop_index(op.f('ix_userclinic_id'), table_name='userclinic')
    op.drop_table('userclinic')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
