"""add wallet creation requests

Revision ID: 920ea50e49c4
Revises: 7291c76b408b
Create Date: 2026-05-20 10:36:34.435833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920ea50e49c4'
down_revision: Union[str, Sequence[str], None] = '7291c76b408b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_creation_requests',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('scope_type', sa.Enum('DSO', 'CLINIC', name='wallet_creation_scope_type_enum'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('dso_id', sa.UUID(), nullable=True),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('wallet_type', sa.Enum('DSO_TREASURY', 'CLINIC', name='wallet_creation_wallet_type_enum'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('initiated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUCCEEDED', 'FAILED', name='wallet_creation_request_status_enum'), server_default='IN_PROGRESS', nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dso_id'], ['Dsos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_creation_requests_clinic_id'), 'wallet_creation_requests', ['clinic_id'], unique=False)
    op.create_index('ix_wallet_creation_requests_clinic_status', 'wallet_creation_requests', ['clinic_id', 'status'], unique=False)
    op.create_index(op.f('ix_wallet_creation_requests_dso_id'), 'wallet_creation_requests', ['dso_id'], unique=False)
    op.create_index('ix_wallet_creation_requests_dso_status', 'wallet_creation_requests', ['dso_id', 'status'], unique=False)
    op.create_index(op.f('ix_wallet_creation_requests_id'), 'wallet_creation_requests', ['id'], unique=True)
    op.create_index(op.f('ix_wallet_creation_requests_idempotency_key'), 'wallet_creation_requests', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_wallet_creation_requests_initiated_by_user_id'), 'wallet_creation_requests', ['initiated_by_user_id'], unique=False)
    op.create_index('ix_wallet_creation_requests_scope_status', 'wallet_creation_requests', ['scope_type', 'status'], unique=False)
    op.create_index(op.f('ix_wallet_creation_requests_scope_type'), 'wallet_creation_requests', ['scope_type'], unique=False)
    op.create_index(op.f('ix_wallet_creation_requests_status'), 'wallet_creation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_creation_requests_wallet_id'), 'wallet_creation_requests', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_wallet_creation_requests_wallet_type'), 'wallet_creation_requests', ['wallet_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_creation_requests_wallet_type'), table_name='wallet_creation_requests')
    op.drop_index(op.f('ix_wallet_creation_requests_wallet_id'), table_name='wallet_creation_requests')
    op.drop_index(op.f('ix_wallet_creation_requests_status'), table_name='wallet_creation_requests')
    op.drop_index(op.f('ix_wallet_creation_requests_scope_type'), table_name='wallet_creation_requests')
    op.drop_index('ix_wallet_creation_requests_scope_status', table_name='wallet_creation_requests')
    op.drop_index(op.f('ix_wallet_creation_requests_initiated_by_user_id'), table_name='wallet_creation_requests')
    op.drop_index(op.f('ix_wallet_creation_requests_idempotency_key'), table_name='wallet_creation_requests')
    op.drop_index(op.f('ix_wallet_creation_requests_id'), table_name='wallet_creation_requests')
    op.drop_index('ix_wallet_creation_requests_dso_status', table_name='wallet_creation_requests')
    op.drop_index(op.f('ix_wallet_creation_requests_dso_id'), table_name='wallet_creation_requests')
    op.drop_index('ix_wallet_creation_requests_clinic_status', table_name='wallet_creation_requests')
    op.drop_index(op.f('ix_wallet_creation_requests_clinic_id'), table_name='wallet_creation_requests')
    op.drop_table('wallet_creation_requests')
    # ### end Alembic commands ###
