"""add appointment sync logs table

Revision ID: afe59147b6e7
Revises: e5d8c7b6a1f0
Create Date: 2026-03-16 23:25:22.484019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afe59147b6e7'
down_revision: Union[str, Sequence[str], None] = 'e5d8c7b6a1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_events',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('crm_type', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), server_default='received', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_events_id'), 'inbound_events', ['id'], unique=True)
    op.create_table('appointment_sync_logs',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('pat_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('inbound_event_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('CRM_TO_OD', 'OD_TO_CRM', name='sync_direction_enum'), nullable=False),
    sa.Column('appointment_status', sa.String(), nullable=False),
    sa.Column('sync_status', sa.Enum('QUEUED', 'PROCESSING', 'RETRYING', 'PROCESSED', 'FAILED', name='sync_status_enum'), server_default='QUEUED', nullable=False),
    sa.Column('change_key', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('apt_num', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inbound_event_id'], ['inbound_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pat_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_key', name='uq_appointment_sync_logs_change_key')
    )
    op.create_index(op.f('ix_appointment_sync_logs_id'), 'appointment_sync_logs', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_sync_logs_id'), table_name='appointment_sync_logs')
    op.drop_table('appointment_sync_logs')
    op.drop_index(op.f('ix_inbound_events_id'), table_name='inbound_events')
    op.drop_table('inbound_events')
    # ### end Alembic commands ###
