"""add billing tables and sync log billing fields

Revision ID: efd6c4b95fb6
Revises: 0db94ee3923e
Create Date: 2026-04-27 15:39:26.891288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

scope_type_enum = postgresql.ENUM(
    "DSO",
    "CLINIC",
    name="scope_type_enum",
    create_type=False,
)

sync_failure_source_enum = postgresql.ENUM(
    "NONE",
    "CUSTOMER_CONFIGURATION",
    "OPEN_DENTAL",
    "CRM",
    "WEBHOOK",
    "INTERNAL",
    "UNKNOWN",
    name="sync_failure_source_enum",
)


# revision identifiers, used by Alembic.
revision: str = 'efd6c4b95fb6'
down_revision: Union[str, Sequence[str], None] = '0db94ee3923e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('dso_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('parent_wallet_id', sa.UUID(), nullable=True),
    sa.Column('wallet_type', sa.Enum('DSO_TREASURY', 'CLINIC', name='wallet_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DISABLED', 'FAILED', name='wallet_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('external_wallet_id', sa.String(), nullable=True),
    sa.Column('external_wallet_address', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('cached_balance_minor', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('auto_debit_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_balance_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dso_id'], ['Dsos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'wallet_type', name='uq_wallet_clinic_type'),
    sa.UniqueConstraint('dso_id', 'wallet_type', name='up_wallet_dso_type')
    )
    op.create_index(op.f('ix_wallets_auto_debit_enabled'), 'wallets', ['auto_debit_enabled'], unique=False)
    op.create_index(op.f('ix_wallets_clinic_id'), 'wallets', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_wallets_dso_id'), 'wallets', ['dso_id'], unique=False)
    op.create_index(op.f('ix_wallets_external_wallet_address'), 'wallets', ['external_wallet_address'], unique=False)
    op.create_index(op.f('ix_wallets_external_wallet_id'), 'wallets', ['external_wallet_id'], unique=True)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=True)
    op.create_index(op.f('ix_wallets_parent_wallet_id'), 'wallets', ['parent_wallet_id'], unique=False)
    op.create_index(op.f('ix_wallets_status'), 'wallets', ['status'], unique=False)
    op.create_index(op.f('ix_wallets_wallet_type'), 'wallets', ['wallet_type'], unique=False)
    op.create_index('ix_walletss_dso_clinic_parent', 'wallets', ['dso_id', 'clinic_id', 'parent_wallet_id'], unique=False)
    op.create_table('billing_subscriptions',
    sa.Column('scope_type', scope_type_enum,  nullable=False),
    sa.Column('dso_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('TRAILING', 'ACTIVE', 'PAST_DUE', 'UNPAID', 'CANCELLED', name='subscription_status_enum'), server_default='TRAILING', nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', name='Billing_cycle_enum'), server_default='MONTHLY', nullable=False),
    sa.Column('payment_provider', sa.Enum('TOROFORGE', 'STRIPE', 'INTERNAL', name='payment_provider_enum'), server_default='STRIPE', nullable=False),
    sa.Column('plan_code', sa.Enum('STARTER', 'BRONZE', 'PREMIUM', name='billing_plan_code_enum'), nullable=False),
    sa.Column('base_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('included_sync_threshold', sa.Integer(), nullable=False),
    sa.Column('external_subscription_id', sa.String(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dso_id'], ['Dsos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscriptions_clinic_id'), 'billing_subscriptions', ['clinic_id'], unique=False)
    op.create_index('ix_billing_subscriptions_clinic_status', 'billing_subscriptions', ['clinic_id', 'status'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_dso_id'), 'billing_subscriptions', ['dso_id'], unique=False)
    op.create_index('ix_billing_subscriptions_dso_status', 'billing_subscriptions', ['dso_id', 'status'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_external_subscription_id'), 'billing_subscriptions', ['external_subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_id'), 'billing_subscriptions', ['id'], unique=True)
    op.create_index(op.f('ix_billing_subscriptions_payment_provider'), 'billing_subscriptions', ['payment_provider'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_plan_code'), 'billing_subscriptions', ['plan_code'], unique=False)
    op.create_index('ix_billing_subscriptions_scope_status', 'billing_subscriptions', ['scope_type', 'status'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_scope_type'), 'billing_subscriptions', ['scope_type'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_status'), 'billing_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_wallet_id'), 'billing_subscriptions', ['wallet_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('dso_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('feature_code', sa.Enum('MESSAGING', 'ELIGIBILITY', 'TICKET_AUTOMATION', 'SYNC_OVERAGE', name='usage_feature_code_enum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('billing_status', sa.Enum('PENDING', 'CHARGED', 'FAILED', 'REFUNDED', 'WAIVED', name='usage_billing_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('charge_provider', sa.Enum('TOROFORGE', 'STRIPE', 'INTERNAL', name='usage_charge_provider_enum'), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dso_id'], ['Dsos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_billing_status'), 'usage_events', ['billing_status'], unique=False)
    op.create_index(op.f('ix_usage_events_charge_provider'), 'usage_events', ['charge_provider'], unique=False)
    op.create_index('ix_usage_events_clinic_feature_created', 'usage_events', ['clinic_id', 'feature_code', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_clinic_id'), 'usage_events', ['clinic_id'], unique=False)
    op.create_index('ix_usage_events_dso_feature_created', 'usage_events', ['dso_id', 'feature_code', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_dso_id'), 'usage_events', ['dso_id'], unique=False)
    op.create_index(op.f('ix_usage_events_feature_code'), 'usage_events', ['feature_code'], unique=False)
    op.create_index(op.f('ix_usage_events_id'), 'usage_events', ['id'], unique=True)
    op.create_index(op.f('ix_usage_events_wallet_id'), 'usage_events', ['wallet_id'], unique=False)
    op.create_table('wallet_ledger_entries',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_wallet_id', sa.UUID(), nullable=True),
    sa.Column('transaction_group_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('TOP_UP', 'TRANSFER_OUT', 'TRANSFER_IN', 'SUBSCRIPTION_CHARGE', 'USAGE_CHARGE', 'REFUND', 'ADJUSTMENT', name='ledger_entry_type_enum'), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='ledger_direction_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'FAILED', 'REVERSED', name='ledger_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('balance_after_minor', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.Enum('TOROFORGE', 'STRIPE', 'INTERNAL', name='ledger_payment_provider_enum'), server_default='INTERNAL', nullable=False),
    sa.Column('external_transaction_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_ledger_entries_counterparty_wallet_id'), 'wallet_ledger_entries', ['counterparty_wallet_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_direction'), 'wallet_ledger_entries', ['direction'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_entry_type'), 'wallet_ledger_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_external_transaction_id'), 'wallet_ledger_entries', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_id'), 'wallet_ledger_entries', ['id'], unique=True)
    op.create_index(op.f('ix_wallet_ledger_entries_idempotency_key'), 'wallet_ledger_entries', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_wallet_ledger_entries_provider'), 'wallet_ledger_entries', ['provider'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_status'), 'wallet_ledger_entries', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_transaction_group_id'), 'wallet_ledger_entries', ['transaction_group_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_wallet_id'), 'wallet_ledger_entries', ['wallet_id'], unique=False)
    op.create_index('ix_wallet_ledger_reference', 'wallet_ledger_entries', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_wallet_ledger_wallet_created', 'wallet_ledger_entries', ['wallet_id', 'created_at'], unique=False)
    op.create_table('wallet_transfers',
    sa.Column('from_wallet_id', sa.UUID(), nullable=False),
    sa.Column('to_wallet_id', sa.UUID(), nullable=False),
    sa.Column('initiated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELED', name='wallet_transfer_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('external_transaction_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transfers_external_transaction_id'), 'wallet_transfers', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_wallet_transfers_from_wallet_id'), 'wallet_transfers', ['from_wallet_id'], unique=False)
    op.create_index(op.f('ix_wallet_transfers_id'), 'wallet_transfers', ['id'], unique=True)
    op.create_index(op.f('ix_wallet_transfers_idempotency_key'), 'wallet_transfers', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_wallet_transfers_initiated_by_user_id'), 'wallet_transfers', ['initiated_by_user_id'], unique=False)
    op.create_index(op.f('ix_wallet_transfers_status'), 'wallet_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_transfers_to_wallet_id'), 'wallet_transfers', ['to_wallet_id'], unique=False)
    op.create_table('daily_sync_usage_summaries',
    sa.Column('dso_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('total_sync_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('successful_syncs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('customer_configuration_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('open_dental_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('crm_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('webhook_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('internal_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unknown_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('counted_usage_units', sa.Integer(), server_default='0', nullable=False),
    sa.Column('included_units_applied', sa.Integer(), server_default='0', nullable=False),
    sa.Column('billable_overage_units', sa.Integer(), server_default='0', nullable=False),
    sa.Column('aggregation_status', sa.Enum('PENDING', 'CHARGED', 'FAILED', 'NO_OVERAGE', name='daily_sync_aggregation_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('usage_event_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dso_id'], ['Dsos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usage_event_id'], ['usage_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'usage_date', name='uq_daily_sync_usage_clinic_date')
    )
    op.create_index(op.f('ix_daily_sync_usage_summaries_aggregation_status'), 'daily_sync_usage_summaries', ['aggregation_status'], unique=False)
    op.create_index(op.f('ix_daily_sync_usage_summaries_clinic_id'), 'daily_sync_usage_summaries', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_daily_sync_usage_summaries_dso_id'), 'daily_sync_usage_summaries', ['dso_id'], unique=False)
    op.create_index(op.f('ix_daily_sync_usage_summaries_id'), 'daily_sync_usage_summaries', ['id'], unique=True)
    op.create_index(op.f('ix_daily_sync_usage_summaries_usage_date'), 'daily_sync_usage_summaries', ['usage_date'], unique=False)
    op.create_index(op.f('ix_daily_sync_usage_summaries_usage_event_id'), 'daily_sync_usage_summaries', ['usage_event_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('dso_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('TOROFORGE', 'STRIPE', 'INTERNAL', name='payment_transaction_provider_enum'), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('external_payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='payment_transaction_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['registered_clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dso_id'], ['Dsos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing_subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_transactions_clinic_created', 'payment_transactions', ['clinic_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_clinic_id'), 'payment_transactions', ['clinic_id'], unique=False)
    op.create_index('ix_payment_transactions_dso_created', 'payment_transactions', ['dso_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_dso_id'), 'payment_transactions', ['dso_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_external_payment_id'), 'payment_transactions', ['external_payment_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_idempotency_key'), 'payment_transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_transactions_provider'), 'payment_transactions', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_transactions_purpose'), 'payment_transactions', ['purpose'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_subscription_id'), 'payment_transactions', ['subscription_id'], unique=False)
    op.create_index('ix_payment_transactions_wallet_created', 'payment_transactions', ['wallet_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_wallet_id'), 'payment_transactions', ['wallet_id'], unique=False)
    bind = op.get_bind()
    sync_failure_source_enum.create(bind, checkfirst=True)

    op.add_column('appointment_sync_logs', sa.Column('failure_source', sync_failure_source_enum,server_default='NONE', nullable=False,))
    op.add_column('appointment_sync_logs', sa.Column('counts_toward_usage', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointment_sync_logs', sa.Column('is_billable', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointment_sync_logs', sa.Column('billing_processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_appointment_sync_logs_counts_toward_usage'), 'appointment_sync_logs', ['counts_toward_usage'], unique=False)
    op.create_index(op.f('ix_appointment_sync_logs_failure_source'), 'appointment_sync_logs', ['failure_source'], unique=False)
    op.create_index(op.f('ix_appointment_sync_logs_is_billable'), 'appointment_sync_logs', ['is_billable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_sync_logs_is_billable'), table_name='appointment_sync_logs')
    op.drop_index(op.f('ix_appointment_sync_logs_failure_source'), table_name='appointment_sync_logs')
    op.drop_index(op.f('ix_appointment_sync_logs_counts_toward_usage'), table_name='appointment_sync_logs')
    op.drop_column('appointment_sync_logs', 'billing_processed_at')
    op.drop_column('appointment_sync_logs', 'is_billable')
    op.drop_column('appointment_sync_logs', 'counts_toward_usage')
    op.drop_column('appointment_sync_logs', 'failure_source')
    sync_failure_source_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_payment_transactions_wallet_id'), table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_wallet_created', table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_subscription_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_purpose'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_provider'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_idempotency_key'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_external_payment_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_dso_id'), table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_dso_created', table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_clinic_id'), table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_clinic_created', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_daily_sync_usage_summaries_usage_event_id'), table_name='daily_sync_usage_summaries')
    op.drop_index(op.f('ix_daily_sync_usage_summaries_usage_date'), table_name='daily_sync_usage_summaries')
    op.drop_index(op.f('ix_daily_sync_usage_summaries_id'), table_name='daily_sync_usage_summaries')
    op.drop_index(op.f('ix_daily_sync_usage_summaries_dso_id'), table_name='daily_sync_usage_summaries')
    op.drop_index(op.f('ix_daily_sync_usage_summaries_clinic_id'), table_name='daily_sync_usage_summaries')
    op.drop_index(op.f('ix_daily_sync_usage_summaries_aggregation_status'), table_name='daily_sync_usage_summaries')
    op.drop_table('daily_sync_usage_summaries')
    op.drop_index(op.f('ix_wallet_transfers_to_wallet_id'), table_name='wallet_transfers')
    op.drop_index(op.f('ix_wallet_transfers_status'), table_name='wallet_transfers')
    op.drop_index(op.f('ix_wallet_transfers_initiated_by_user_id'), table_name='wallet_transfers')
    op.drop_index(op.f('ix_wallet_transfers_idempotency_key'), table_name='wallet_transfers')
    op.drop_index(op.f('ix_wallet_transfers_id'), table_name='wallet_transfers')
    op.drop_index(op.f('ix_wallet_transfers_from_wallet_id'), table_name='wallet_transfers')
    op.drop_index(op.f('ix_wallet_transfers_external_transaction_id'), table_name='wallet_transfers')
    op.drop_table('wallet_transfers')
    op.drop_index('ix_wallet_ledger_wallet_created', table_name='wallet_ledger_entries')
    op.drop_index('ix_wallet_ledger_reference', table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_wallet_id'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_transaction_group_id'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_status'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_provider'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_idempotency_key'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_id'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_external_transaction_id'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_entry_type'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_direction'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_counterparty_wallet_id'), table_name='wallet_ledger_entries')
    op.drop_table('wallet_ledger_entries')
    op.drop_index(op.f('ix_usage_events_wallet_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_feature_code'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_dso_id'), table_name='usage_events')
    op.drop_index('ix_usage_events_dso_feature_created', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_clinic_id'), table_name='usage_events')
    op.drop_index('ix_usage_events_clinic_feature_created', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_charge_provider'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_billing_status'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_billing_subscriptions_wallet_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_status'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_scope_type'), table_name='billing_subscriptions')
    op.drop_index('ix_billing_subscriptions_scope_status', table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_plan_code'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_payment_provider'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_external_subscription_id'), table_name='billing_subscriptions')
    op.drop_index('ix_billing_subscriptions_dso_status', table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_dso_id'), table_name='billing_subscriptions')
    op.drop_index('ix_billing_subscriptions_clinic_status', table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_clinic_id'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    op.drop_index('ix_walletss_dso_clinic_parent', table_name='wallets')
    op.drop_index(op.f('ix_wallets_wallet_type'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_status'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_parent_wallet_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_external_wallet_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_external_wallet_address'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_dso_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_clinic_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_auto_debit_enabled'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
